### PR TITLE
add version to golang.mk

### PR DESCRIPTION
**Pull request by natebrennand**
Add versioning to `golang.mk`.

### CODE REVIEW

**Comment by natebrennand** [comment]
@nathanleiby, assigning you since you initially suggested it.

**Comment by nathanleiby** [comment]
lgtm!

thoughts on adding use of golang.mk and golang.mk version as a report-card check?

**Comment by natebrennand** [comment]
It's already on the checklist!
https://clever.atlassian.net/browse/SCHOOLS-946

**Comment by nathanleiby** [comment]
:+1:

**Pull request merged**
